### ISSUE TITLE
read property 'props' of undefined

### ISSUE THREAD

**Issue by jifeilong9** [hqwlkj/taro-dva-demo#1]
![image](https://user-images.githubusercontent.com/24316291/63777433-acac9b00-c915-11e9-92b7-16610967e5d7.png)
下载源码无修改运行报这个错

**Comment by szy0syz** [comment]
已提pull request~
只是typo，不是bug啦~

**Comment by szy0syz** [comment]
用着楼主的 umi-dva-antd-mobile 很不错，又来支持 taro-dva-demo 😁

**Comment by hqwlkj** [comment]
@szy0syz  感谢支持😁
